[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19"
ron = "0.8"
serde = { version = "1", features = ["derive"] }

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
# fast compilation
opt-level = 1
# slow compilation
# opt-level = 3
